---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform: [1.0.0, latest]
        directories: [".", "examples/cost", "examples/simple", "examples/full"]
    defaults:
      run:
        working-directory: ${{ matrix.directories }}
    steps:
      # yamllint disable-line rule:comments
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # yamllint disable-line rule:comments
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ matrix.terraform }}

      - run: terraform -version

      - run: terraform init -input=false -backend=false

      - run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:comments
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # yamllint disable-line rule:comments
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.config/tflint.hcl') }}

      - name: configure aws credentials
        # yamllint disable-line rule:comments
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_TFLINT_ROLE_ARN }}
          role-session-name: tflint
          aws-region: ${{ secrets.AWS_REGION }}

      - name: install tflint
        run: |
          # renovate: datasource=github-tags depName=terraform-linters/tflint
          tflint_version="v0.45.0"

          curl -o tflint.zip -L \
            https://github.com/terraform-linters/tflint/releases/download/v${tflint_version}/tflint_linux_amd64.zip
          unzip tflint.zip

      - name: Show version
        run: ./tflint --config=.config/tflint.hcl --version

      - name: Init TFLint
        run: ./tflint --config=.config/tflint.hcl --init

      - name: Run TFLint
        run: ./tflint --config=.config/tflint.hcl -f compact
