---
name: Create a release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  # to create protected tags
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@v3.7.3
        with:
          release-type: simple
          signoff: "Matthias Kay <matthias.kay@hlag.com>"
