---
name: Create a release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa # v1
        id: app-token
        with:
          app-id: ${{ vars.GET_TOKEN_APP_ID }}
          private-key: ${{ secrets.GET_TOKEN_APP_PRIVATE_KEY }}
      # bootstrap-sha and release-as needs to be removed after first release
      - name: Release
        # yamllint disable-line rule:line-length
        uses: google-github-actions/release-please-action@c5182cc8b1ba400fc549efce9b4f73c58db4417b  # ratchet:google-github-actions/release-please-action@v3
        with:
          release-type: python
          token: ${{ steps.app-token.outputs.token }}
          pull-request-header: ''
