---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on:
  workflow_call:
#  pull_request_target

jobs:
  pr-auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        with:
          review-message: "Auto approve Renovate PR (organization rule)"
          github-token: ${{ secrets.PAT_FOR_PR_AUTO_APPROVAL }}
