---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:comments
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # yamllint disable-line rule:comments
      - uses: streetsidesoftware/cspell-action@cdaa4625255f2e8d5cc9d06c60ed9b4b0fe4bf03 # v2.20.0
        with:
          config: .config/cspell.json
