---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            json:
              - '**/*.json'

            markdown:
              - '**/*.md'

            renovate-config:
              - 'renovate.json'
              - 'default.json'

            workflow:
              - '.github/workflows/*.yml'
              - '.github/workflows/*.yaml'

            yaml:
              - '**/*.yaml'
              - '**/*.yml'
    outputs:
      json: ${{ steps.changes.outputs.json }}
      markdown: ${{ steps.changes.outputs.markdown }}
      renovate-config: ${{ steps.changes.outputs.renovate-config }}
      workflow: ${{ steps.changes.outputs.workflow }}
      yaml: ${{ steps.changes.outputs.yaml }}

  lint-json:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.json == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run JSON Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

  lint-markdown:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.markdown == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Validate Markdown file
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .config/markdownlint.yml -i CHANGELOG.md "**/*.md"

  lint-renovate:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.renovate-config == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2

  lint-workflow:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.workflow == 'true'
    container:
      image: rhysd/actionlint:1.6.22@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468
      options: --cpus 1 --user root
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Validate Github workflows
        run: |
          mkdir .git
          actionlint -color

  lint-yaml:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.yaml == 'true'
    steps:
      - uses: actions/checkout@v3.3.0
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .config/yamllint.yml
          strict: true
