---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            json:
              - '**/*.json'

            markdown:
              - '**/*.md'

            renovate-config:
              - 'renovate.json'
              - 'default.json'

            template-workflow:
              - 'templates/**/.github/workflows/*.yml'
              - 'templates/**/.github/workflows/*.yaml'

            workflow:
              - '.github/workflows/*.yml'
              - '.github/workflows/*.yaml'

            yaml:
              - '**/*.yaml'
              - '**/*.yml'
    outputs:
      json: ${{ steps.changes.outputs.json }}
      markdown: ${{ steps.changes.outputs.markdown }}
      renovate-config: ${{ steps.changes.outputs.renovate-config }}
      template-workflow: ${{ steps.changes.outputs.workflow }}
      workflow: ${{ steps.changes.outputs.workflow }}
      yaml: ${{ steps.changes.outputs.yaml }}

  lint-json:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.json == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run JSON Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

  lint-markdown:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.markdown == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Markdown file
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .config/markdownlint.yml -i CHANGELOG.md "**/*.md"

  lint-renovate:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.renovate-config == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b7cd2b598bb51d071a2474e98f55cc25f91abec1 # v0.1.3

  lint-workflow:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.workflow == 'true'
    container:
      image: rhysd/actionlint:1.6.26@sha256:2362769b1d75056da70e7af1b12d9e52746f3a123b8f22a4322869e8f2cd45f2
      options: --cpus 1 --user root
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Github workflows
        run: |
          mkdir .git
          actionlint -color

  lint-template-workflow:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.template-workflow == 'true'
    container:
      image: rhysd/actionlint:1.6.26@sha256:2362769b1d75056da70e7af1b12d9e52746f3a123b8f22a4322869e8f2cd45f2
      options: --cpus 1 --user root
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Github workflow templates
        run: |
          mkdir .git

          for file in templates/**/.github/workflows/*.yml; do
            actionlint -color "$file"
          done

  lint-yaml:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.yaml == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: .config/yamllint.yml
          strict: true
