---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  main:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Get Body
        id: get-body
        run: |
          PR_NUMBER=$(echo ${{ github.ref }} | awk 'BEGIN { FS = "/" } ; { print $3 }')
          PR_BODY=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER | jq -r .body)

          echo "body=$PR_BODY" >> "$GITHUB_OUTPUT"

      - name: Spell Check
        run: echo "${{steps.get-body.outputs.body}}"
