---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  main:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Get Body
        run: |
          PR_NUMBER=$(echo ${{ github.ref }} | awk 'BEGIN { FS = "/" } ; { print $3 }')
          curl -v -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER

      - uses: actions/github-script@v6
        id: get-body
        with:
          result-encoding: string
          script: |
            return await github.rest.pulls.get({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            }).data.body

      - name: Spell Check
        run: echo "${{steps.get-body.outputs.result}}"
