---
name: Create a release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        # yamllint disable-line rule:comments
        uses: google-github-actions/release-please-action@514bc6cdae71484c998108f2136a8f5e4c62b9b9 # v3.7.3
        with:
          # to create protected tags
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          release-type: simple
          signoff: "Matthias Kay <matthias.kay@hlag.com>"
