---
name: PR opened

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_welcome_message_callable.yml@3a102f6e2e5326bde1f4b3ad8b9b4354323aef41
    secrets: inherit
