---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_linter_callable.yml@43e6750b1d3d9f95a066f982db24432d8d1903c2
    secrets: inherit
