---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_linter_callable.yml@83145674c405973a9d1797a6b39887670938315b
    secrets: inherit
