---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_pull_request_callable.yml@83145674c405973a9d1797a6b39887670938315b
    secrets: inherit
